### PR TITLE
The Black Purple Button

### PR DESCRIPTION
**Pull request by ghost**
I have added a black button to commemorate the Purple website as part of the Affinity Program.

I hope you like it! :D

### CODE REVIEW

**Comment by JeffAbrahamson** [comment]
You commited this to your master branch, which makes it really hard to evaluate without pulling it.  Can you push it to a branch instead?

Also, I'm in the (exceedingly slow) process of redesigning the site.  It's not at all obvious, so don't feel bad, but the way it works now is this:
* the www-subdomain directory is historical
* the www directory is the actual site, but it is auto-generated
* the src directory generates the site with the script `purple.py` and which I run with `src/run.sh`

So all that means that the file you really want to edit is `in/affinity/index.html` and add the png in `in/affinity/`.  Feel free to add something to the copyright line to give yourself credit for this little nod to goth purple fans and everything that that 1980's subculture has given us 40 years on.

**Comment by JaredMFProgramming** [comment]
Okay! :D

**Comment by JaredMFProgramming** [comment]
All fixed! ;)

**Comment by JaredMFProgramming** [comment]
Hmmm...is the Leesa branch the right one?

**Comment by JeffAbrahamson** [comment]
I'm currently using the Leesa branch, but I'll just merge what I need from master.  Master should be the authoritative.

I'm slow right now because I'm swamped at work.

**Comment by JeffAbrahamson** [comment]
OK, I've cherry picked this to master.  I also took the liberty of squashing your three commits into one with a single coherent commit message, at the same time removing the two www-subdomain files that shouldn't have been included (because they are historical).

There's a minor software issue on the host that's serving purple that is making deployment fail.  I'll sort this out in a bit.

Thanks for the commit!

**Comment by JaredMFProgramming** [comment]
Okay! :)

**Pull request merged**
